### PR TITLE
Fix documentation linking

### PR DESCRIPTION
**Pull request by Lotes**
I still discovered some missing links since the refactoring of the docs.

I will continue on Monday to search for more gaps.

### CODE REVIEW

**Review by msujew — COMMENTED** [review]
Question: Why keep `lexis` in the url for the lexing recipes?

Also, you missed one:
https://github.com/eclipse-langium/langium-website/blob/b2759fcaae2022da2fb5cfea22b8bebc39f71bf4/hugo/content/docs/reference/grammar-language.md?plain=1#L80

Otherwise, looks good to me 👍

**Comment by Lotes** [comment]
I think it would be good to have a script doing this checking task.

**Comment by Lotes** [comment]
@msujew I fixed the two findings of you, the remaining issues can be fixed in #237 .

**Review by msujew — APPROVED** [review]
LGTM 👍

**Pull request merged**
