### PR TITLE
Fix wrong type in example

### PR DESCRIPTION
**Pull request by didrikmunther**

### CODE REVIEW

**Review by msujew — APPROVED** [review]
Ah, thanks!

**Review by msujew — COMMENTED** [review]
I just noticed that the ECA wasn't signed yet (most likely because the commit was actually created by GitHub and not manually via the git client). Due to legal reasons, contributors to Langium (or rather all Eclipse Foundation projects) must sign the [Eclipse Contribution Agreement](https://www.eclipse.org/legal/eca/) before we're able to merge the changes (no matter how small).

@didrikmunther Can you do that? Otherwise I will just create a PR myself with the necessary changes and close this one.

**Comment by didrikmunther** [comment]
> I just noticed that the ECA wasn't signed yet (most likely because the commit was actually created by GitHub and not manually via the git client). Due to legal reasons, contributors to Langium (or rather all Eclipse Foundation projects) must sign the [Eclipse Contribution Agreement](https://www.eclipse.org/legal/eca/) before we're able to merge the changes (no matter how small).
> 
> @didrikmunther Can you do that? Otherwise I will just create a PR myself with the necessary changes and close this one.

I'd rather not do that for a change this small. Feel free to create a PR yourself with this change!

**Comment by msujew** [comment]
@didrikmunther Thank you, that's understandable. I've created https://github.com/eclipse-langium/langium-website/pull/260, and this PR will be automatically closed once the other one is merged.

**Pull request closed without merging**
