### PR TITLE
Fix 404 page's styling

### LINKED ISSUE #236: Improve 404 Page and Dead Link Handling
After re-designing the layout of the documentation, we've ended up with a number of dead links. For example, the old getting-started link now redirects to a 404. This in itself is somewhat okay, but the 404 page is very broken looking, as can be seen below.
Screenshot 2024-05-24 at 10 06 40

The 404 page template needs to be corrected, and in cases where we know a link has moved, and it is appropriate to redirect to the new link location, we should do so.

### PR DESCRIPTION
**Pull request by Lotes**
Fixes #236

### CODE REVIEW

**Comment by Lotes** [comment]
This is still draft, because I need to test as a deployment ftm because on local mode it does not show up the custom 404. The problem so far is that the `others.html` partial includes paths to CSS that are not correct on subpages like "/docs/xxx"...

**Comment by Lotes** [comment]
Bah, it seems I cannot test it really on a preview server. The 404 page is a result of the HTTP server, which redirects to `404.html` (GH-Preview-Pages does not). So what was missing? The base URL T_T...
I think when we release the changed flag, it will work. But I definitely cannot test it locally.

**Review by msujew — COMMENTED** [review]
This seems to break the GitHub PR preview:
https://eclipse-langium.github.io/langium-previews/pr-previews/pr-238/docs/

**Comment by Lotes** [comment]
> This seems to break the GitHub PR preview: https://eclipse-langium.github.io/langium-previews/pr-previews/pr-238/docs/

True. We need to set the correct base url before we are building. Otherwise it would be `https://eclipse-langium.github.io/langium-previews/pr-previews` instead of `https://eclipse-langium.github.io/langium-previews/pr-previews/pr-xxx`.

**Comment by montymxb** [comment]
I've peeked at this too and it feels like hugo isn't responding to a myriad of ways to set a custom 404. The usual locations in layout, static, or even modifying the theme don't seem to have effect (notably the theme's own 404 isn't applied as expected). There can be a few reasons for this based on how we've customized the app, but we're also using an older version from about 3 years ago. I'm not sure how easily we could upgrade, but it might be worth checking if some newer version of hugo makes it easier to resolve this.

**Comment by Lotes** [comment]
I am closing this PR. No idea how to check this, without breaking something.

**Pull request closed without merging**
